### PR TITLE
2017 samples sync

### PR DESCRIPTION
**Pull request by gourangakole**
Hello @efeyazgan 

Could you please take a look for the ``WW, WZ and ZZ`` samples? 

also @adeiorio, please check Single top samples 
https://github.com/gourangakole/ttc_bar/blob/75dba168a725a09e2f244aa5d8e5ba8db418151e/crab/bhplus_samples2017.json#L25-L29

if all are Ok or not particularly the ``DR`` or ``DS`` as we discussed yesterday.

### CODE REVIEW

**Comment by efeyazgan** [comment]
I paste the table here:

Capture d’écran 2024-01-31 à 14 09 32

You can get the dataset names from here (for example for single top we use the sampel with no DR or DS.

**Comment by gourangakole** [comment]
Thanks a lot @efeyazgan that answer's all my questions.
I shall update the json.

**Comment by adeiorio** [comment]
Hi @gourangakole I tried to have a look at the TOP recommendation on which samples to use for tW but I didn't manage to find any. In any case in the current json you have tbarW with the DS scheme and the tW without it. At least we should be consistent.

**Comment by efeyazgan** [comment]
As in the table I sent above, it looks like when we do not care high precision for single top, we use
```
ST tW top 5f NoFullyHadronicDecays TuneCP5 13TeV-powheg-pythia8
ST tW antitop 5f NoFullyHadronicDecays TuneCP5 13TeV-powheg-pythia8
```

**Comment by gourangakole** [comment]
Hi @efeyazgan Just to make sure:
I included ``/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM`` for ttZToLNu

see the list below:
```
[gkole@lxplus708:crab]$ dasgoclient --query "dataset dataset=/TTZToLLNuNu_M-10_TuneCP5*_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9*/NANOAODSIM"
/TTZToLLNuNu_M-10_TuneCP5CR1_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
/TTZToLLNuNu_M-10_TuneCP5CR2_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
/TTZToLLNuNu_M-10_TuneCP5down_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
/TTZToLLNuNu_M-10_TuneCP5up_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
```
not sure about the sample you mention with ``PSWeight`` ? 

same comment for 
``/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM``

Rest are taken care.

**Comment by efeyazgan** [comment]
You included the correct one (i.e.: /TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM), the others are for color-reconnection and underlying-event variations. I forgot to detele PSweights - that should be remaining from fall17 or so...
I'll correct in the AN. 

 /TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM is the correct one as well. 

thanks.

**Pull request merged**
