### PR TITLE
WW dps samples 2016

### PR DESCRIPTION
**Pull request by gourangakole**

### CODE REVIEW

**Comment by gourangakole** [comment]
Hi @efeyazgan what do for DPS sample

should we keep like this?
```
/WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
/WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v2/NANOAODSIM
/WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
/WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/NANOAODSIM
```
I shall fix then, 
https://github.com/ExtraYukawa/ttc_bar/blob/2c836fab9832c3df217bc87b5a02a4e04a42d327/crab/samples2016.json#L51

Also I shall update these as well
(they are NanoV8)
https://github.com/ExtraYukawa/ttc_bar/blob/2c836fab9832c3df217bc87b5a02a4e04a42d327/crab/samples2017.json#L63

https://github.com/ExtraYukawa/ttc_bar/blob/2c836fab9832c3df217bc87b5a02a4e04a42d327/crab/samples2018.json#L53

**Comment by efeyazgan** [comment]
Thanks

**Comment by gourangakole** [comment]
Hi @efeyazgan lets then close this ?

**Comment by efeyazgan** [comment]
right

**Pull request closed without merging**
