### PR TITLE
Crab, samples, and configuration for bHplus

### PR DESCRIPTION
**Pull request by gourangakole**
- Trigger samples for 2016,
- crab configuration supports
- some minor

### CODE REVIEW

**Comment by gourangakole** [comment]
This is all running fines for all year.
Just Merging a 2018, 2016(both)

So I can merge if you do not see any issues.

**Comment by efeyazgan** [comment]
At this point, I get this complaint:
```
source init.sh 2016apv #(FOR 2016APV) 
Initing
/afs/cern.ch/work/e/efe/bHplus/CMSSW_13_2_6/src/PhysicsTools/NanoAODTools/python/postprocessing/
Initiating setup for 2016apv......
Updating pileup
Updating prefiring correction
Updateing JME correction
cleaning unused files
Updating BJet related
cp: cannot stat '/afs/cern.ch/work/e/efe/bHplus/CMSSW_13_2_6/src/PhysicsTools/NanoAODTools/python/postprocessing//analysis/others/for_btv/DeepJet_106XUL16preVFPSF_v2_skimmed.csv': No such file or directory
...
```
Is that OK?

**Comment by efeyazgan** [comment]
And following README blindly doesn't work...

**Comment by efeyazgan** [comment]
This is minor but the link here 
```
    If you want to keep GEN info in the ntuples, in https://github.com/ExtraYukawa/ttc_bar/blob/lep_mvaID/crab/keep_and_drop.txt remove the following line:
```
 should be updated in README. 

For the rest, we should determine what is missing/inconsistent in README.

**Comment by efeyazgan** [comment]
But may be better is to merge this one and deal with the rest in another PR. So, merging.

**Comment by gourangakole** [comment]
> At this point, I get this complaint:
> 
> ```
> source init.sh 2016apv #(FOR 2016APV) 
> Initing
> /afs/cern.ch/work/e/efe/bHplus/CMSSW_13_2_6/src/PhysicsTools/NanoAODTools/python/postprocessing/
> Initiating setup for 2016apv......
> Updating pileup
> Updating prefiring correction
> Updateing JME correction
> cleaning unused files
> Updating BJet related
> cp: cannot stat '/afs/cern.ch/work/e/efe/bHplus/CMSSW_13_2_6/src/PhysicsTools/NanoAODTools/python/postprocessing//analysis/others/for_btv/DeepJet_106XUL16preVFPSF_v2_skimmed.csv': No such file or directory
> ...
> ```
> 
> Is that OK?

I think you missed some commit 
I was there already:

https://github.com/ExtraYukawa/ttc_bar/pull/53/commits/75cc93d43dded38c864864c4ae5e68d95c97dcce

**Pull request merged**
