### PR TITLE
interfearence samples for rtc04 (3 years)

### PR DESCRIPTION
**Pull request by gourangakole**
To run on crab to get ntuple:

@efeyazgan @menglu21 please check if you found some typo :) 

so that you have set up to run on 2017 and 2018.
I shall be doing 2016 apv and postAPV.

### CODE REVIEW

**Comment by efeyazgan** [comment]
Thanks. They look OK but we should also process the rtu04 samples: [/TAToTTQ_MA-*-*GeV_TuneCP5_13TeV_G2HDM-rtu04-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FTAToTTQ_MA-*-*GeV_TuneCP5_13TeV_G2HDM-rtu04-madgraphMLM-pythia8%2FRunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1%2FNANOAODSIM)

**Comment by gourangakole** [comment]
> Thanks. They look OK but we should also process the rtu04 samples: [/TAToTTQ_MA-*-*GeV_TuneCP5_13TeV_G2HDM-rtu04-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FTAToTTQ_MA-*-*GeV_TuneCP5_13TeV_G2HDM-rtu04-madgraphMLM-pythia8%2FRunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1%2FNANOAODSIM)

Yes, forgot about it. on the way of adding it. Thank you.

**Comment by gourangakole** [comment]
Hi @efeyazgan added the rtu04 samples. 
Should be ok, but please have a look.

**Comment by efeyazgan** [comment]
Thanks! They look OK.

**Pull request merged**
